apiVersion: v1
kind: Service
metadata:
  name: siniestros-ml-service
spec:
  selector:
    app: siniestros-ml
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}